@startuml

entity 顧客マスタ {
  + 顧客ID
  ---
  顧客名
  郵便番号
  住所
  電話番号
  FAX番号
}

entity 注文テーブル {
  + 注文ID
  ---
  # 顧客ID (FK)
  # 配送方法 (FK)
  # 決済方法 (FK)
  注文日時
  配送希望日
  お届け先名
  お届け先住所
  合計金額
  消費税額
}

entity 配送方法マスタ {
  + 配送方法ID
  ---
  配送方法
  配送業者名
  配送業者TEL
  配送業者住所
}

entity 決済方法マスタ {
  + 決済方法ID
  ---
  決済方法
  決済業者名
  決済業者TEL
  決済業者住所
}

entity 注文明細テーブル {
  + 注文ID
  + 明細番号
  ---
  SKU
  注文数
  税抜価格
  税込価格
}

entity SKUマスタ {
  + SKU
  ---
  # 商品ID (FK)
  カラー
  サイズ
  重量
  販売単価
  仕入単価
}

entity 商品マスタ {
  + 商品ID
  ---
  商品名
  原産国
  # 仕入先ID (FK)
  商品カテゴリ
  配送必要日数
}

注文テーブル }o-l-|| 顧客マスタ
注文テーブル }o--|| 配送方法マスタ
注文テーブル }o--|| 決済方法マスタ
注文テーブル ||-r-|{ 注文明細テーブル
注文明細テーブル }o--|| SKUマスタ
SKUマスタ }|-r-|| 商品マスタ


@enduml
